### ISSUE TITLE
nsml submit 관련 질문

### ISSUE THREAD

**Issue by skfn20** [Naver-AI-Hackathon/AI-Speech#72]
submit 한 경우에 test-submit으로dataset의 경로를 잡아주도록 했는데 
아래와 같은 오류가 발생합니다. 
submit을 할 때에는 test 데이터에 대한 접근을 따로 하지 않아도 되는건가요?
아니면 어떤 방식으로 해야하나요?

args.mode :  test -> args.mode를 찍어본 부분

Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 377, in main
    with open(data_list, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/sr-hack-2019-dataset/test_submit'
User session exited

**Comment by HanSeokhyeon** [comment]
```
[hack]$ nsml submit [SESSION] [CHECKPOINT]

# baseline에서 기본으로 저장하는 체크포인트 목록
#
# 'model' : 매 epoch마다 자동 저장되는 체크포인트
# 'best' : evaluation loss가 가장 좋은 모델을 저장하는 체크포인트
# 
# 저장된 체크포인트 목록 확인 방법
#
# nsml model ls [SESSION] 
```

https://github.com/clovaai/speech_hackathon_2019#2-leader-board-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0

README에 잘 나와있네요!
 
`nsml submit teamXXX/sr-hack-2019-dataset/XXX 'best'`

따로 args.mode 안바꾸고 위와 같이 submit하니 저는 잘 됩니다.

**Comment by skfn20** [comment]
친절한 답변 감사합니다! 
저도 처음에는 args.mode 안 바꾸고 알려주신 방법처럼 했었는데 
계속 internal server error라고 떠서 다른 코드들을 추가하니까 저렇게 나오네요ㅠㅠ

**Comment by HanSeokhyeon** [comment]
internal server error는 보통 현재 가능한 resource보다 더 많은 gpu나 cpu를 사용했을때 뜨던데 혹시 그런 오류는 아닌가요?

**Comment by skfn20** [comment]
gpu랑 cpu 사용량을 줄인 후에도 안 되는 것을 보면 그런 오류에는 해당하지 않나봐요ㅠㅠ

**Comment by HanSeokhyeon** [comment]
에러 내용을 좀 더 자세히 볼 수 있을까요??

**Comment by skfn20** [comment]
git clone해서 모델을 바로 받고 난 후에 학습이 완료된 세션을 대상으로
nsml submit --test로 submit을 하니 터미널에서 아래와 같은 로그가 찍혀서 
submit인 경우에는 args.mode =  test이길래 
if args.mode ==test 인 경우에 
datapath를  test-submit에 접근해서 결과를 보려한 결과
맨 처음에 올렸던 에러가 발생하였습니다. 
submit을 하는 경우를 위한 코드가 따로 필요한 것인가요?
  
Traceback (most recent call last):
  File "main.py", line 416, in <module>
    main()
  File "main.py", line 362, in main
    with open(data_list, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/sr-hack-2019-dataset/train/train_data/data_list.csv'
User session exited

**Comment by HanSeokhyeon** [comment]
음... 저는 `nsml submit --test`라는 커맨드를 입력한 적은 없어서요.. `nsml submit --test`이 유효한 방법인가요? nsml documentation에도 `nsml submit 세션이름 체크포인트` 밖에 안보이네요..

https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/load_model.html

**Comment by skfn20** [comment]
해결했습니다
신경써서 답변해주셔서 감사합니다!!
